// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using National_Museum_2.Context;

#nullable disable

namespace National_Museum_2.Migrations
{
    [DbContext(typeof(MuseumDbContext))]
    [Migration("20240920215848_newColumn")]
    partial class newColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("National_Museum_2.Model.Contact", b =>
                {
                    b.Property<int>("contactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contactId"));

                    b.Property<string>("contactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_IduserId")
                        .HasColumnType("int");

                    b.HasKey("contactId");

                    b.HasIndex("user_IduserId");

                    b.ToTable("contact");
                });

            modelBuilder.Entity("National_Museum_2.Model.Gender", b =>
                {
                    b.Property<int>("genderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("genderId"));

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genderId");

                    b.ToTable("gender");
                });

            modelBuilder.Entity("National_Museum_2.Model.IdentificationType", b =>
                {
                    b.Property<int>("identificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("identificationTypeId"));

                    b.Property<string>("Identification_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("identificationTypeId");

                    b.ToTable("identificationType");
                });

            modelBuilder.Entity("National_Museum_2.Model.PermissionXUserType", b =>
                {
                    b.Property<int>("permissionXUserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permissionXUserTypeId"));

                    b.Property<int>("user_Type_IduserTypeId")
                        .HasColumnType("int");

                    b.HasKey("permissionXUserTypeId");

                    b.HasIndex("user_Type_IduserTypeId");

                    b.ToTable("permissionXUserType");
                });

            modelBuilder.Entity("National_Museum_2.Model.Permissions", b =>
                {
                    b.Property<int>("permissionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permissionsId"));

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionXUserType_IdpermissionXUserTypeId")
                        .HasColumnType("int");

                    b.HasKey("permissionsId");

                    b.HasIndex("PermissionXUserType_IdpermissionXUserTypeId");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("National_Museum_2.Model.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("birthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gender_IdgenderId")
                        .HasColumnType("int");

                    b.Property<string>("identificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("identificationType_IdidentificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("lastNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_Type_IduserTypeId")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("gender_IdgenderId");

                    b.HasIndex("identificationType_IdidentificationTypeId");

                    b.HasIndex("user_Type_IduserTypeId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("National_Museum_2.Model.UserType", b =>
                {
                    b.Property<int>("userTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userTypeId"));

                    b.Property<string>("userType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userTypeId");

                    b.ToTable("userType");
                });

            modelBuilder.Entity("National_Museum_2.Model.Contact", b =>
                {
                    b.HasOne("National_Museum_2.Model.User", "user_Id")
                        .WithMany()
                        .HasForeignKey("user_IduserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_Id");
                });

            modelBuilder.Entity("National_Museum_2.Model.PermissionXUserType", b =>
                {
                    b.HasOne("National_Museum_2.Model.UserType", "user_Type_Id")
                        .WithMany()
                        .HasForeignKey("user_Type_IduserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_Type_Id");
                });

            modelBuilder.Entity("National_Museum_2.Model.Permissions", b =>
                {
                    b.HasOne("National_Museum_2.Model.PermissionXUserType", "PermissionXUserType_Id")
                        .WithMany()
                        .HasForeignKey("PermissionXUserType_IdpermissionXUserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionXUserType_Id");
                });

            modelBuilder.Entity("National_Museum_2.Model.User", b =>
                {
                    b.HasOne("National_Museum_2.Model.Gender", "gender_Id")
                        .WithMany()
                        .HasForeignKey("gender_IdgenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.IdentificationType", "identificationType_Id")
                        .WithMany()
                        .HasForeignKey("identificationType_IdidentificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.UserType", "user_Type_Id")
                        .WithMany()
                        .HasForeignKey("user_Type_IduserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gender_Id");

                    b.Navigation("identificationType_Id");

                    b.Navigation("user_Type_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
