// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using National_Museum_2.Context;

#nullable disable

namespace National_Museum_2.Migrations
{
    [DbContext(typeof(MuseumDbContext))]
    [Migration("20241021051340_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("National_Museum_2.Model.ArtObject", b =>
                {
                    b.Property<int>("artObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("artObjectId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("category_Id")
                        .HasColumnType("int");

                    b.Property<string>("cost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("exhibition_Id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stateId")
                        .HasColumnType("int");

                    b.Property<int>("state_Id")
                        .HasColumnType("int");

                    b.HasKey("artObjectId");

                    b.HasIndex("category_Id");

                    b.HasIndex("exhibition_Id");

                    b.HasIndex("stateId");

                    b.ToTable("artObject");
                });

            modelBuilder.Entity("National_Museum_2.Model.ArtRoom", b =>
                {
                    b.Property<int>("artRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("artRoomId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("collection_Id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("location_Id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberExhibitions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("artRoomId");

                    b.HasIndex("collection_Id");

                    b.HasIndex("location_Id");

                    b.ToTable("artRoom");
                });

            modelBuilder.Entity("National_Museum_2.Model.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("National_Museum_2.Model.Collection", b =>
                {
                    b.Property<int>("collectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("collectionId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("collectionId");

                    b.ToTable("collection");
                });

            modelBuilder.Entity("National_Museum_2.Model.Contact", b =>
                {
                    b.Property<int>("contactId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("contactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_Id")
                        .HasColumnType("int");

                    b.HasKey("contactId");

                    b.ToTable("contact");
                });

            modelBuilder.Entity("National_Museum_2.Model.Employees", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("hiringDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("maintenanceId")
                        .HasColumnType("int");

                    b.Property<int>("maintenance_Id")
                        .HasColumnType("int");

                    b.Property<int>("typeEmployee_Id")
                        .HasColumnType("int");

                    b.Property<int>("user_Id")
                        .HasColumnType("int");

                    b.Property<int>("workShedule_Id")
                        .HasColumnType("int");

                    b.HasKey("employeeId");

                    b.HasIndex("maintenanceId");

                    b.HasIndex("typeEmployee_Id");

                    b.HasIndex("user_Id");

                    b.HasIndex("workShedule_Id");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("National_Museum_2.Model.EmployeesXArtRoom", b =>
                {
                    b.Property<int>("employeesXArtRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeesXArtRoomId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("artRoomId")
                        .HasColumnType("int");

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.HasKey("employeesXArtRoomId");

                    b.HasIndex("artRoomId");

                    b.HasIndex("employeeId");

                    b.ToTable("employeesXArtRoom");
                });

            modelBuilder.Entity("National_Museum_2.Model.Exhibition", b =>
                {
                    b.Property<int>("exhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("exhibitionId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("artRoom_Id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("exhibitionId");

                    b.HasIndex("artRoom_Id");

                    b.ToTable("exhibition");
                });

            modelBuilder.Entity("National_Museum_2.Model.GameProgress", b =>
                {
                    b.Property<int>("gameProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gameProgressId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gameProgress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gameProgressId");

                    b.ToTable("gameProgresses");
                });

            modelBuilder.Entity("National_Museum_2.Model.GameState", b =>
                {
                    b.Property<int>("gameStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gameStateId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("gameState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gameStateId");

                    b.ToTable("gameStates");
                });

            modelBuilder.Entity("National_Museum_2.Model.Games", b =>
                {
                    b.Property<int>("gameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gameId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("gameDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("gameProgress_Id")
                        .HasColumnType("int");

                    b.Property<int>("gameState_Id")
                        .HasColumnType("int");

                    b.Property<string>("gameTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("punctuation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("scenary_Id")
                        .HasColumnType("int");

                    b.Property<int>("user_Id")
                        .HasColumnType("int");

                    b.HasKey("gameId");

                    b.HasIndex("gameProgress_Id");

                    b.HasIndex("gameState_Id");

                    b.HasIndex("scenary_Id");

                    b.HasIndex("user_Id");

                    b.ToTable("games");
                });

            modelBuilder.Entity("National_Museum_2.Model.Gender", b =>
                {
                    b.Property<int>("genderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("genderId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genderId");

                    b.ToTable("gender");
                });

            modelBuilder.Entity("National_Museum_2.Model.HistoricMaintenance", b =>
                {
                    b.Property<int>("historicMaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("historicMaintenanceId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModicationBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("artObject_Id")
                        .HasColumnType("int");

                    b.Property<int>("cost")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("maintenance_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("starDate")
                        .HasColumnType("datetime2");

                    b.HasKey("historicMaintenanceId");

                    b.ToTable("historicMaintenance");
                });

            modelBuilder.Entity("National_Museum_2.Model.HistoricTickets", b =>
                {
                    b.Property<int>("historicTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("historicTicketId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModicationBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<int>("paymentMethod_Id")
                        .HasColumnType("int");

                    b.Property<int>("ticketType_Id")
                        .HasColumnType("int");

                    b.Property<int>("ticketXCollection_Id")
                        .HasColumnType("int");

                    b.Property<int>("ticket_Id")
                        .HasColumnType("int");

                    b.Property<int>("user_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("visitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("historicTicketId");

                    b.ToTable("historicTickets");
                });

            modelBuilder.Entity("National_Museum_2.Model.HistoricUser", b =>
                {
                    b.Property<int>("historicUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("historicUserId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModicationBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("birthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gender_Id")
                        .HasColumnType("int");

                    b.Property<string>("identificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("identificationType_Id")
                        .HasColumnType("int");

                    b.Property<string>("lastNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_Id")
                        .HasColumnType("int");

                    b.Property<int>("user_Type_Id")
                        .HasColumnType("int");

                    b.HasKey("historicUserId");

                    b.ToTable("historicUser");
                });

            modelBuilder.Entity("National_Museum_2.Model.IdentificationType", b =>
                {
                    b.Property<int>("identificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("identificationTypeId"));

                    b.Property<string>("Identification_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("identificationTypeId");

                    b.ToTable("identificationType");
                });

            modelBuilder.Entity("National_Museum_2.Model.Location", b =>
                {
                    b.Property<int>("locationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("locationId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("locationId");

                    b.ToTable("location");
                });

            modelBuilder.Entity("National_Museum_2.Model.Maintenance", b =>
                {
                    b.Property<int>("maintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maintenanceId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("artObject_Id")
                        .HasColumnType("int");

                    b.Property<int>("cost")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("starDate")
                        .HasColumnType("datetime2");

                    b.HasKey("maintenanceId");

                    b.HasIndex("artObject_Id");

                    b.ToTable("maintenance");
                });

            modelBuilder.Entity("National_Museum_2.Model.MaintenanceXEmployee", b =>
                {
                    b.Property<int>("maintenanceXEmployee_Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("employee_Id")
                        .HasColumnType("int");

                    b.Property<int>("maitenance_Id")
                        .HasColumnType("int");

                    b.HasKey("maintenanceXEmployee_Id");

                    b.HasIndex("employee_Id");

                    b.ToTable("maintenanceXEmployee");
                });

            modelBuilder.Entity("National_Museum_2.Model.PaymentMethod", b =>
                {
                    b.Property<int>("paymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymentMethodId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("paymentMethodId");

                    b.ToTable("paymentMethods");
                });

            modelBuilder.Entity("National_Museum_2.Model.PermissionXUserType", b =>
                {
                    b.Property<int>("permissionXUserTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("permissions_Id")
                        .HasColumnType("int");

                    b.Property<int>("userType_Id")
                        .HasColumnType("int");

                    b.HasKey("permissionXUserTypeId");

                    b.HasIndex("userType_Id");

                    b.ToTable("permissionXUserType");
                });

            modelBuilder.Entity("National_Museum_2.Model.Permissions", b =>
                {
                    b.Property<int>("permissionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permissionsId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("permissionsId");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("National_Museum_2.Model.Scenary", b =>
                {
                    b.Property<int>("scenaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("scenaryId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("achievementsobtained")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("order")
                        .HasColumnType("int");

                    b.Property<string>("scenaryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("scenaryId");

                    b.ToTable("scenary");
                });

            modelBuilder.Entity("National_Museum_2.Model.State", b =>
                {
                    b.Property<int>("stateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stateId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stateId");

                    b.ToTable("state");
                });

            modelBuilder.Entity("National_Museum_2.Model.TicketType", b =>
                {
                    b.Property<int>("ticketTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ticketTypeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("ticketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ticketTypeId");

                    b.ToTable("ticketType");
                });

            modelBuilder.Entity("National_Museum_2.Model.TicketXCollection", b =>
                {
                    b.Property<int>("ticketXCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ticketXCollectionId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Ticket_Id")
                        .HasColumnType("int");

                    b.Property<int>("collection_Id")
                        .HasColumnType("int");

                    b.HasKey("ticketXCollectionId");

                    b.HasIndex("Ticket_Id");

                    b.HasIndex("collection_Id");

                    b.ToTable("ticketXCollection");
                });

            modelBuilder.Entity("National_Museum_2.Model.Tickets", b =>
                {
                    b.Property<int>("ticketId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<int>("paymentMethod_Id")
                        .HasColumnType("int");

                    b.Property<int>("ticketType_Id")
                        .HasColumnType("int");

                    b.Property<int>("user_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("visitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ticketId");

                    b.HasIndex("paymentMethod_Id");

                    b.HasIndex("ticketType_Id");

                    b.ToTable("ticket");
                });

            modelBuilder.Entity("National_Museum_2.Model.TypeEmployee", b =>
                {
                    b.Property<int>("typeEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("typeEmployeeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("typeEmployee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("typeEmployeeId");

                    b.ToTable("typeEmployee");
                });

            modelBuilder.Entity("National_Museum_2.Model.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("birthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gender_Id")
                        .HasColumnType("int");

                    b.Property<string>("identificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("identificationType_Id")
                        .HasColumnType("int");

                    b.Property<string>("lastNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_Type_Id")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("gender_Id");

                    b.HasIndex("identificationType_Id");

                    b.HasIndex("user_Type_Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("National_Museum_2.Model.UserType", b =>
                {
                    b.Property<int>("userTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userTypeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("userType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userTypeId");

                    b.ToTable("userType");
                });

            modelBuilder.Entity("National_Museum_2.Model.WorkShedule", b =>
                {
                    b.Property<int>("workSheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("workSheduleId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("workShedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("workSheduleId");

                    b.ToTable("workShedule");
                });

            modelBuilder.Entity("National_Museum_2.Model.ArtObject", b =>
                {
                    b.HasOne("National_Museum_2.Model.Category", "category")
                        .WithMany("artObjects")
                        .HasForeignKey("category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.Exhibition", "exhibition")
                        .WithMany("artObjects")
                        .HasForeignKey("exhibition_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.State", "state")
                        .WithMany("artObjects")
                        .HasForeignKey("stateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("exhibition");

                    b.Navigation("state");
                });

            modelBuilder.Entity("National_Museum_2.Model.ArtRoom", b =>
                {
                    b.HasOne("National_Museum_2.Model.Collection", "collection")
                        .WithMany("artRooms")
                        .HasForeignKey("collection_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.Location", "location")
                        .WithMany("artRooms")
                        .HasForeignKey("location_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("collection");

                    b.Navigation("location");
                });

            modelBuilder.Entity("National_Museum_2.Model.Contact", b =>
                {
                    b.HasOne("National_Museum_2.Model.User", "user")
                        .WithMany("contacts")
                        .HasForeignKey("contactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("National_Museum_2.Model.Employees", b =>
                {
                    b.HasOne("National_Museum_2.Model.Maintenance", "maintenance")
                        .WithMany()
                        .HasForeignKey("maintenanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.TypeEmployee", "typeEmployee")
                        .WithMany("employees")
                        .HasForeignKey("typeEmployee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.User", "user")
                        .WithMany("employees")
                        .HasForeignKey("user_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.WorkShedule", "workShedule")
                        .WithMany("employees")
                        .HasForeignKey("workShedule_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("maintenance");

                    b.Navigation("typeEmployee");

                    b.Navigation("user");

                    b.Navigation("workShedule");
                });

            modelBuilder.Entity("National_Museum_2.Model.EmployeesXArtRoom", b =>
                {
                    b.HasOne("National_Museum_2.Model.ArtRoom", "artRoom")
                        .WithMany("employeesXArtRoom")
                        .HasForeignKey("artRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.Employees", "employee")
                        .WithMany("employeesXArtRooms")
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("artRoom");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("National_Museum_2.Model.Exhibition", b =>
                {
                    b.HasOne("National_Museum_2.Model.ArtRoom", "artRoom")
                        .WithMany("exhibition")
                        .HasForeignKey("artRoom_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("artRoom");
                });

            modelBuilder.Entity("National_Museum_2.Model.Games", b =>
                {
                    b.HasOne("National_Museum_2.Model.GameProgress", "gameProgress")
                        .WithMany("games")
                        .HasForeignKey("gameProgress_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.GameState", "gameState")
                        .WithMany("games")
                        .HasForeignKey("gameState_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.Scenary", "scenary")
                        .WithMany("games")
                        .HasForeignKey("scenary_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.User", "user")
                        .WithMany("games")
                        .HasForeignKey("user_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gameProgress");

                    b.Navigation("gameState");

                    b.Navigation("scenary");

                    b.Navigation("user");
                });

            modelBuilder.Entity("National_Museum_2.Model.Maintenance", b =>
                {
                    b.HasOne("National_Museum_2.Model.ArtObject", "artObject")
                        .WithMany("maintenance")
                        .HasForeignKey("artObject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("artObject");
                });

            modelBuilder.Entity("National_Museum_2.Model.MaintenanceXEmployee", b =>
                {
                    b.HasOne("National_Museum_2.Model.Employees", "employees")
                        .WithMany("maintenanceXEmployee")
                        .HasForeignKey("employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.Maintenance", "maitenance")
                        .WithMany("maintenanceXEmployees")
                        .HasForeignKey("maintenanceXEmployee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employees");

                    b.Navigation("maitenance");
                });

            modelBuilder.Entity("National_Museum_2.Model.PermissionXUserType", b =>
                {
                    b.HasOne("National_Museum_2.Model.Permissions", "permissions")
                        .WithMany("permissionXUserTypes")
                        .HasForeignKey("permissionXUserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.UserType", "userType")
                        .WithMany("permissionsXUserType")
                        .HasForeignKey("userType_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("permissions");

                    b.Navigation("userType");
                });

            modelBuilder.Entity("National_Museum_2.Model.TicketXCollection", b =>
                {
                    b.HasOne("National_Museum_2.Model.Tickets", "Ticket")
                        .WithMany("ticketXCollections")
                        .HasForeignKey("Ticket_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.Collection", "collection")
                        .WithMany("ticketXCollections")
                        .HasForeignKey("collection_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("collection");
                });

            modelBuilder.Entity("National_Museum_2.Model.Tickets", b =>
                {
                    b.HasOne("National_Museum_2.Model.PaymentMethod", "paymentMethod")
                        .WithMany("tickets")
                        .HasForeignKey("paymentMethod_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.User", "user")
                        .WithMany("tickets")
                        .HasForeignKey("ticketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.TicketType", "ticketType")
                        .WithMany("tickets")
                        .HasForeignKey("ticketType_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paymentMethod");

                    b.Navigation("ticketType");

                    b.Navigation("user");
                });

            modelBuilder.Entity("National_Museum_2.Model.User", b =>
                {
                    b.HasOne("National_Museum_2.Model.Gender", "gender")
                        .WithMany("users")
                        .HasForeignKey("gender_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.IdentificationType", "identificationType")
                        .WithMany("users")
                        .HasForeignKey("identificationType_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.UserType", "user_Type")
                        .WithMany("users")
                        .HasForeignKey("user_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gender");

                    b.Navigation("identificationType");

                    b.Navigation("user_Type");
                });

            modelBuilder.Entity("National_Museum_2.Model.ArtObject", b =>
                {
                    b.Navigation("maintenance");
                });

            modelBuilder.Entity("National_Museum_2.Model.ArtRoom", b =>
                {
                    b.Navigation("employeesXArtRoom");

                    b.Navigation("exhibition");
                });

            modelBuilder.Entity("National_Museum_2.Model.Category", b =>
                {
                    b.Navigation("artObjects");
                });

            modelBuilder.Entity("National_Museum_2.Model.Collection", b =>
                {
                    b.Navigation("artRooms");

                    b.Navigation("ticketXCollections");
                });

            modelBuilder.Entity("National_Museum_2.Model.Employees", b =>
                {
                    b.Navigation("employeesXArtRooms");

                    b.Navigation("maintenanceXEmployee");
                });

            modelBuilder.Entity("National_Museum_2.Model.Exhibition", b =>
                {
                    b.Navigation("artObjects");
                });

            modelBuilder.Entity("National_Museum_2.Model.GameProgress", b =>
                {
                    b.Navigation("games");
                });

            modelBuilder.Entity("National_Museum_2.Model.GameState", b =>
                {
                    b.Navigation("games");
                });

            modelBuilder.Entity("National_Museum_2.Model.Gender", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("National_Museum_2.Model.IdentificationType", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("National_Museum_2.Model.Location", b =>
                {
                    b.Navigation("artRooms");
                });

            modelBuilder.Entity("National_Museum_2.Model.Maintenance", b =>
                {
                    b.Navigation("maintenanceXEmployees");
                });

            modelBuilder.Entity("National_Museum_2.Model.PaymentMethod", b =>
                {
                    b.Navigation("tickets");
                });

            modelBuilder.Entity("National_Museum_2.Model.Permissions", b =>
                {
                    b.Navigation("permissionXUserTypes");
                });

            modelBuilder.Entity("National_Museum_2.Model.Scenary", b =>
                {
                    b.Navigation("games");
                });

            modelBuilder.Entity("National_Museum_2.Model.State", b =>
                {
                    b.Navigation("artObjects");
                });

            modelBuilder.Entity("National_Museum_2.Model.TicketType", b =>
                {
                    b.Navigation("tickets");
                });

            modelBuilder.Entity("National_Museum_2.Model.Tickets", b =>
                {
                    b.Navigation("ticketXCollections");
                });

            modelBuilder.Entity("National_Museum_2.Model.TypeEmployee", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("National_Museum_2.Model.User", b =>
                {
                    b.Navigation("contacts");

                    b.Navigation("employees");

                    b.Navigation("games");

                    b.Navigation("tickets");
                });

            modelBuilder.Entity("National_Museum_2.Model.UserType", b =>
                {
                    b.Navigation("permissionsXUserType");

                    b.Navigation("users");
                });

            modelBuilder.Entity("National_Museum_2.Model.WorkShedule", b =>
                {
                    b.Navigation("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
