// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using National_Museum_2.Context;

#nullable disable

namespace National_Museum_2.Migrations
{
    [DbContext(typeof(MuseumDbContext))]
    partial class MuseumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("National_Museum_2.Model.Collection", b =>
                {
                    b.Property<int>("collectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("collectionId"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("collectionId");

                    b.ToTable("collection");
                });

            modelBuilder.Entity("National_Museum_2.Model.Contact", b =>
                {
                    b.Property<int>("contactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contactId"));

                    b.Property<string>("contactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_IduserId")
                        .HasColumnType("int");

                    b.HasKey("contactId");

                    b.HasIndex("user_IduserId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("National_Museum_2.Model.Employees", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("employeesXArtRoom_IdemployeesXArtRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("hiringDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("maintenance_IdmaintenanceId")
                        .HasColumnType("int");

                    b.Property<int>("typeEmployee_IdtypeEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("workShedule_IdworkSheduleId")
                        .HasColumnType("int");

                    b.HasKey("employeeId");

                    b.HasIndex("employeesXArtRoom_IdemployeesXArtRoomId");

                    b.HasIndex("maintenance_IdmaintenanceId");

                    b.HasIndex("typeEmployee_IdtypeEmployeeId");

                    b.HasIndex("workShedule_IdworkSheduleId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("National_Museum_2.Model.EmployeesXArtRoom", b =>
                {
                    b.Property<int>("employeesXArtRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeesXArtRoomId"));

                    b.Property<int>("artRoomId")
                        .HasColumnType("int");

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.HasKey("employeesXArtRoomId");

                    b.ToTable("employeesXArtRoom");
                });

            modelBuilder.Entity("National_Museum_2.Model.Gender", b =>
                {
                    b.Property<int>("genderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("genderId"));

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genderId");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("National_Museum_2.Model.IdentificationType", b =>
                {
                    b.Property<int>("identificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("identificationTypeId"));

                    b.Property<string>("Identification_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("identificationTypeId");

                    b.ToTable("IdentificationType");
                });

            modelBuilder.Entity("National_Museum_2.Model.Maintenance", b =>
                {
                    b.Property<int>("maintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maintenanceId"));

                    b.Property<int>("ArtObject_Id")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StarDate")
                        .HasColumnType("datetime2");

                    b.HasKey("maintenanceId");

                    b.ToTable("maintenances");
                });

            modelBuilder.Entity("National_Museum_2.Model.PermissionXUserType", b =>
                {
                    b.Property<int>("permissionXUserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permissionXUserTypeId"));

                    b.Property<int>("user_Type_IduserTypeId")
                        .HasColumnType("int");

                    b.HasKey("permissionXUserTypeId");

                    b.HasIndex("user_Type_IduserTypeId");

                    b.ToTable("PermissionXUserType");
                });

            modelBuilder.Entity("National_Museum_2.Model.Permissions", b =>
                {
                    b.Property<int>("permissionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permissionsId"));

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionXUserType_IdpermissionXUserTypeId")
                        .HasColumnType("int");

                    b.HasKey("permissionsId");

                    b.HasIndex("PermissionXUserType_IdpermissionXUserTypeId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("National_Museum_2.Model.TypeEmployee", b =>
                {
                    b.Property<int>("typeEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("typeEmployeeId"));

                    b.Property<string>("typeEmployee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("typeEmployeeId");

                    b.ToTable("typeEmployee");
                });

            modelBuilder.Entity("National_Museum_2.Model.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("birthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gender_IdgenderId")
                        .HasColumnType("int");

                    b.Property<string>("identificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("identificationType_IdidentificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("lastNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_Type_IduserTypeId")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("gender_IdgenderId");

                    b.HasIndex("identificationType_IdidentificationTypeId");

                    b.HasIndex("user_Type_IduserTypeId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("National_Museum_2.Model.UserType", b =>
                {
                    b.Property<int>("userTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userTypeId"));

                    b.Property<string>("userType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userTypeId");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("National_Museum_2.Model.WorkShedule", b =>
                {
                    b.Property<int>("workSheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("workSheduleId"));

                    b.Property<string>("workShedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("workSheduleId");

                    b.ToTable("workShedule");
                });

            modelBuilder.Entity("National_Museum_2.Model.Contact", b =>
                {
                    b.HasOne("National_Museum_2.Model.User", "user_Id")
                        .WithMany()
                        .HasForeignKey("user_IduserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_Id");
                });

            modelBuilder.Entity("National_Museum_2.Model.Employees", b =>
                {
                    b.HasOne("National_Museum_2.Model.EmployeesXArtRoom", "employeesXArtRoom_Id")
                        .WithMany()
                        .HasForeignKey("employeesXArtRoom_IdemployeesXArtRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.Maintenance", "maintenance_Id")
                        .WithMany()
                        .HasForeignKey("maintenance_IdmaintenanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.TypeEmployee", "typeEmployee_Id")
                        .WithMany()
                        .HasForeignKey("typeEmployee_IdtypeEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.WorkShedule", "workShedule_Id")
                        .WithMany()
                        .HasForeignKey("workShedule_IdworkSheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employeesXArtRoom_Id");

                    b.Navigation("maintenance_Id");

                    b.Navigation("typeEmployee_Id");

                    b.Navigation("workShedule_Id");
                });

            modelBuilder.Entity("National_Museum_2.Model.PermissionXUserType", b =>
                {
                    b.HasOne("National_Museum_2.Model.UserType", "user_Type_Id")
                        .WithMany()
                        .HasForeignKey("user_Type_IduserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_Type_Id");
                });

            modelBuilder.Entity("National_Museum_2.Model.Permissions", b =>
                {
                    b.HasOne("National_Museum_2.Model.PermissionXUserType", "PermissionXUserType_Id")
                        .WithMany()
                        .HasForeignKey("PermissionXUserType_IdpermissionXUserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionXUserType_Id");
                });

            modelBuilder.Entity("National_Museum_2.Model.User", b =>
                {
                    b.HasOne("National_Museum_2.Model.Gender", "gender_Id")
                        .WithMany()
                        .HasForeignKey("gender_IdgenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.IdentificationType", "identificationType_Id")
                        .WithMany()
                        .HasForeignKey("identificationType_IdidentificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("National_Museum_2.Model.UserType", "user_Type_Id")
                        .WithMany()
                        .HasForeignKey("user_Type_IduserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gender_Id");

                    b.Navigation("identificationType_Id");

                    b.Navigation("user_Type_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
